AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  FixityEventRule

  SAM Template for Execute Fixity Steps Function

Parameters:
    Region:
      Type: String
      Default: "us-east-1"
    DatabaseName:
      Type: String
      Default: "DatabaseName"
    TableName:
      Type: String
      Default: "TableName"
    FixityOutputBucket:
      Type: String
      Default: "FixityOutputBucket"
    ResultBucket:
      Type: String
      Default: "ResultBucket"
    WorkGroupName:
      Type: String
      Default: "primary"
    StateMachineName:
      Type: String
      Default: "StateMachineName"
    StateMachineArn:
      Type: String
      Default: "StateMachineArn"
    DayPeriod:
      Type: Number
      Default: 90

Resources:
  GlueManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GlueManagedPolicyForFixity
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "glue:GetTable"
            Resource:
              - "arn:aws:glue:*:*:database/*"
              - "arn:aws:glue:*:*:catalog"
              - "arn:aws:glue:*:*:table/*"

  ExecuteFixityStepsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fixitycheck/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      MemorySize: 2048
      Timeout: 120
      Policies:
        - AthenaQueryPolicy:
            WorkGroupName: !Ref WorkGroupName
        - S3WritePolicy:
            BucketName: !Ref ResultBucket
        - S3ReadPolicy:
            BucketName: !Ref ResultBucket
        - S3ReadPolicy:
            BucketName: !Ref FixityOutputBucket
        - StepFunctionsExecutionPolicy:
            StateMachineName: !Ref StateMachineName
        - !Ref GlueManagedPolicy

      Environment:
          Variables:
            Region: !Ref Region
            DatabaseName: !Ref DatabaseName
            TableName: !Ref TableName
            FixityOutputBucket: !Ref FixityOutputBucket
            ResultBucket: !Ref ResultBucket
            StateMachineArn: !Ref StateMachineArn
            DayPeriod: !Ref DayPeriod

Outputs:
  ExecuteFixityStepsFunction:
    Description: "Execute Fixity Steps Function ARN"
    Value: !GetAtt ExecuteFixityStepsFunction.Arn
  ExecuteFixityStepsFunctionIamRole:
    Description: "Implicit IAM Role created for Execute Fixity Steps Function"
    Value: !GetAtt ExecuteFixityStepsFunctionRole.Arn
